services:
  init:
    image: busybox
    command: |
      sh -c "
        # Fix permissions for Elasticsearch data/log dirs
        chown 1000:0 /usr/share/elasticsearch/data &&
        chown 1000:0 /usr/share/elasticsearch/logs &&

        # Fix permissions for Cassandra data/log dirs
        chown -R 999:999 /var/lib/cassandra &&
        chown -R 999:999 /var/log/cassandra &&

        # Create AxonOps logs dir
        chown -R 9988:9988 /var/log/axonops
      "
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
      - ./logs/elasticsearch:/usr/share/elasticsearch/logs
      - ./data/cassandra:/var/lib/cassandra
      - ./logs/cassandra:/var/log/cassandra
      - ./logs/axonops:/var/log/axonops

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.27
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - 'ES_JAVA_OPTS=-Xms8g -Xmx8g'
    deploy:
      resources:
        limits:
          memory: 12G
        reservations:
          memory: 8G
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
      - ./logs/elasticsearch:/usr/share/elasticsearch/logs
    depends_on:
      init:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD-SHELL", "curl -sS http://127.0.0.1:9200/_cluster/health?wait_for_status=yellow\\&timeout=5s || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 90s

  cassandra:
    image: cassandra:4.1
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped
    entrypoint: |
      sh -c "sed -i 's/^batch_size_warn_threshold:.*$/batch_size_warn_threshold: 64KiB/; s/^batch_size_fail_threshold:.*$/batch_size_fail_threshold: 640KiB/' /etc/cassandra/cassandra.yaml && exec /usr/local/bin/docker-entrypoint.sh"
    volumes:
      - ./data/cassandra:/var/lib/cassandra
      - ./logs/cassandra:/var/log/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=axonops-cluster
      - MAX_HEAP_SIZE=8g
      - HEAP_NEWSIZE=800m
    deploy:
      resources:
        limits:
          memory: 12G
        reservations:
          memory: 8G
    ports:
      - "9042:9042"
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "nodetool statusbinary | grep -E '^running$'"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 90s

  axon-server:
    image: registry.axonops.com/axonops-public/axonops-docker/axon-server:latest
    restart: unless-stopped
    ports:
      - "1888:1888"
    depends_on:
      elasticsearch:
        condition: service_healthy
      cassandra:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-sf", "127.0.0.1:8080"]
      interval: 10s
      timeout: 5s
      start_period: 10s
    volumes:
        - ./axon-server.yml:/etc/axonops/axon-server.yml:ro
        - ./logs/axonops:/var/log/axonops

  axon-dash:
    image: registry.axonops.com/axonops-public/axonops-docker/axon-dash:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      axon-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-sf", "127.0.0.1:3000"]
      interval: 10s
      timeout: 5s
      start_period: 10s
    volumes:
      - ./axon-dash.yml:/etc/axonops/axon-dash.yml:ro
      - ./logs/axonops:/var/log/axonops
